"""chatsystem

Revision ID: 7d89a686b08c
Revises: 2cdbfb86575e
Create Date: 2025-10-20 11:35:45.109602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d89a686b08c'
down_revision: Union[str, None] = '2cdbfb86575e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('token_budgeting_summary', sa.String(), nullable=True),
    sa.Column('token_budgeting_message_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['token_budgeting_message_id'], ['messages.id'], name='fk_conversation_first_message', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_summary_embedding_ivfflat', table_name='knowledgebase_bc_summaries', postgresql_using='hnsw')
    op.create_index('idx_summary_embedding_hnsw', 'knowledgebase_bc_summaries', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_smallchunk_embedding_ivfflat', table_name='knowledgebase_smallchunks', postgresql_using='hnsw')
    op.create_index('idx_smallchunk_embedding_hnsw', 'knowledgebase_smallchunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_smallchunk_embedding_hnsw', table_name='knowledgebase_smallchunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_smallchunk_embedding_ivfflat', 'knowledgebase_smallchunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index('idx_summary_embedding_hnsw', table_name='knowledgebase_bc_summaries', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_summary_embedding_ivfflat', 'knowledgebase_bc_summaries', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
