"""conversation message feedback and rating

Revision ID: c678c7ee9c58
Revises: e282a336c467
Create Date: 2025-10-22 23:52:36.188503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c678c7ee9c58'
down_revision: Union[str, None] = 'e282a336c467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('rating', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'feedback')
    op.drop_column('messages', 'rating')
    # ### end Alembic commands ###
