"""conversation updated_at field

Revision ID: e282a336c467
Revises: 434f792ffb4e
Create Date: 2025-10-22 15:44:30.998510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e282a336c467'
down_revision: Union[str, None] = '434f792ffb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key('fk_conversation_first_message', 'conversations', 'messages', ['token_budgeting_message_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversation_first_message', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'updated_at')
    # ### end Alembic commands ###
